# This is not currently used, but it is how I will configure the codebase
# TODO: Load with OmegaConf from default.yaml
data:
  datasets: 
    - 500p_avl # contains the re-annotated videos in training split
  num_frames: 9
  #norm_type: imagenet # can be imagenet or clip

model:
  type: classifier # which module to use
  backbone_name: clip_ViT-B/16 # VideoMAEv2Base # clip_ViT-B/32
  #backbone_pretrained_ckpt: /data/clinical_mae/vit_b_hybrid_pt_800e/checkpoint-51.pth
  head: linear

trainer:
  lr: 4e-5
  batch_size: 1
  max_epochs: 20
  num_frozen_epochs: 0
  head_weight_decay: 0.0
  num_workers: cpus-4 # os.cpu_count() - 2
  backbone_weight_decay: 0.00
  backbone_lr_multiplier: 0.0
  accumulate_grad_batches: 64
  check_val_every_n_epoch: 5
  skip_test: True

logger:
  log_every_n_steps: 10
