# This is not currently used, but it is how I will configure the codebase
# TODO: Load with OmegaConf from default.yaml
data:
  datasets: 
    - 500p_new0 # contains the re-annotated videos in training split
  num_frames: 16
  #norm_type: imagenet # can be imagenet or clip

model:
  type: captioner # which module to use
  backbone_name: VideoMAEv2Base # clip_ViT-B/32
  backbone_pretrained_ckpt: /data/pretrained_models/vit_b_k710_dl_from_giant.pth
  text_decoder_name: opt_125m
  head: linear
  head_dropout: 0.00
  text_first: True
  use_start_token_for_caption: False
  prompt: ""

trainer:
  lr: 1e-4
  batch_size: 1
  max_epochs: 16
  num_frozen_epochs: 0
  backbone_lr_multiplier: 0.00
  text_decoder_lr_multiplier: 0.00
  head_weight_decay: 0.00
  backbone_weight_decay: 0.00
  prompt_lr_multiplier: 0.00
  prompt_weight_decay: 0.00
  precision: 32
  num_workers: cpus-4
  accumulate_grad_batches: 64

logger:
  log_every_n_steps: 10
