program: train.py
method: random  # or grid, random, bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  fast_run:
    values: [False] # use special a100 setting for torch.set_float32_matmul_precision("high")
  use_sweep:
    values: [True]
  config: 
    values: [configs/contrastive/500p.yaml] # This is the config file to use
  lr:
    min: 0.00001
    max: 0.001
  num_frames:
    values: [16]
  backbone_name:
    values: [clip_ViT-B/32]
  head:
    values: [None, linear]
  head_dropout:
    min: 0.0
    max: 0.7
  head_weight_decay:
    min: 0.0
    max: 0.1
  backbone_weight_decay:
    min: 0.0
    max: 0.05
  text_encoder_weight_decay:
    min: 0.0
    max: 0.05
  num_frozen_epochs:
    values: [0, 1]
  max_epochs:
    values: [5] # Do longer run next
  backbone_lr_multiplier:
    min: 0.00001
    max: 1.0
  text_encoder_lr_multiplier:
    min: 0.00001
    max: 1.0
  # Add other parameters you want to tune
