# This is not currently used, but it is how I will configure the codebase
# TODO: Load with OmegaConf from default.yaml
data:
  datasets: 
    - ucf101 # TODO: Detect number of classes
  num_frames: 16

classifier:
  backbone_name: clip_ViT-B/16
  head: linear
  classifier_head_weight_decay: 0.0
  backbone_weight_decay: 0.0

trainer:
  lr: 1e-4
  batch_size: 16
  max_epochs: 10
  num_frozen_epochs: 2
  backbone_lr_multiplier: 0.00001
  precision: 32

logger:
  log_every_n_steps: 10
