# Extremely stable training
data:
  datasets: 
    - diving48 
  num_frames: 16

model:
  type: classifier # which module to use
  backbone_name: clip_ViT-B/16
  head: linear
  head_dropout: 0.0
  head_weight_decay: 0.0
  backbone_weight_decay: 0.0

trainer:
  lr: 1e-4
  max_epochs: 20
  num_frozen_epochs: 0
  batch_size: 4
  backbone_lr_multiplier: 1e-1
  accumulate_grad_batches: 4


logger:
  log_every_n_steps: 10
