program: train.py
method: random  # or grid, random, bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  fast_run:
    values: [True] # use special a100 setting for torch.set_float32_matmul_precision("high")
  use_sweep:
    values: [True]
  config: 
    values: [configs/classification/diving48.yaml] # This is the config file to use
  backbone_lr_multiplier:
    values: [1e-1, 1e-2, 1e-3, 1e-4]
  # Add other parameters you want to tune
