program: train.py
method: grid  # or grid, random, bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  fast_run:
    values: [True] # use special a100 setting for torch.set_float32_matmul_precision("high")
  use_sweep:
    values: [True]
  config: 
    values: [configs/classification/diving48.yaml] # This is the config file to use
  backbone_name:
    values: ["dinov2_ViT-S/14", "dinov2_ViT-B/14", "clip_ViT-B/16"]

